[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = ".netlify/edge-functions"
  autoLaunch = false

[[edge_functions]]
  path = "/*"
  function = "server"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/cors-america/*"
  to = "https://www.oxfordlearnersdictionaries.com/search/american_english/direct/?q=:splat"
  status = 301
  force = true