 [[redirects]]
  from = "https://www.oxfordlearnersdictionaries.com/search/american_english/*"
  to = "https://www.oxfordlearnersdictionaries.com/definition/american_english/*"
  status = 302
  force = true