[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = ".netlify/edge-functions"
  autoLaunch = false

[[edge_functions]]
  path = "/*"
  function = "server"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/cors-america/*"
  to = "https://www.getdailyart.com/en/21/paul-signac/the-red-buoy-saint-tropez"
  status = 301
  force = true
  
[[redirects]]
  from = "/cors-cambridge/*"
  to = "https://dictionary.cambridge.org/dictionary/english/:splat"
  status = 302
  force = true