[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = ".netlify/edge-functions"
  autoLaunch = false

[[edge_functions]]
  path = "/*"
  function = "server"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/cors-proxy/*"
  to = ":splat"
  status = 200
  force = true