[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = ".netlify/edge-functions"
  functions = "src/netlify/functions/hello"

[[edge_functions]]
  path = "/*"
  function = "server"

[functions]
  node_bundler = "esbuild"
