[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = ".netlify/edge-functions"
  functions = "src/functions/netlify-cors"

[[edge_functions]]
  path = "/*"
  function = "server"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/netlify-cors"
  status = 200