[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = ".netlify/edge-functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[edge_functions]]
  path = "/*"
  function = "server"

[[redirects]]
  from = "/_server/*"
  to = "/src/functions/netlify-cors"
  status = 200